set autochdir
set autoindent  
set backspace=indent,eol,start
set cindent  
set encoding=utf-8 fileencodings=ucs-born,utf-8,cp936
set hlsearch  
set imcmdline  
set incsearch
set laststatus=2
set linebreak
set modeline  
set nobackup
set nocompatible
set nu  
set previewwindow  
set ruler  
set shiftwidth=4
set showcmd  
set showfulltag  
set showmatch
set showmode  
set smartcase  
set smartindent  
set softtabstop=4
set tabstop=4
set vb
syntax on
